export enum TextLoadingActions {
    REQUESTED = 'TEXT_REQUESTED',
    LOADED = 'TEXT_LOADED',
    ERROR = 'TEXT_LOADING_ERROR',
}

export enum MyStackActions {
    REQUESTED = 'MY_STACK_REQUESTED',
    LOADED = 'MY_STACK_LOADED',
    ERROR = 'MY_STACK_LOADING_ERROR',
}

export enum AuthActions {
    AUTH_COOKIE_START_READING = 'AUTH_COOKIE_START_READING',
    TOKEN_FROM_COOKIE_READ = 'TOKEN_FROM_COOKIE_READ',
    AUTH_COOKIE_NOT_FOUND = 'AUTH_COOKIE_NOT_FOUND',

    LOGIN_REQUESTED = 'LOGIN_REQUESTED',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',

    LOGGED_OUT = 'LOGGED_OUT',
}
